export async function POST(request) {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    return Response.json(
      { error: "Server configuration error: Missing GEMINI_API_KEY" },
      { status: 500 }
    );
  }

  try {
    const { messages, systemPrompt, model } = await request.json();
    const modelId = model || "gemini-2.0-flash";

    // Convert messages to Gemini format
    const chatMessages = messages.filter((m) => m.role !== "system");

    // Sanitize: merge consecutive same-role messages
    const sanitized = [];
    let lastRole = null;
    for (const msg of chatMessages) {
      const role = msg.role === "assistant" ? "model" : "user";
      if (role === lastRole) {
        sanitized[sanitized.length - 1].parts[0].text += "\n\n" + msg.content;
      } else {
        sanitized.push({ role, parts: [{ text: msg.content }] });
        lastRole = role;
      }
    }

    // Ensure starts with user
    if (sanitized.length > 0 && sanitized[0].role === "model") {
      sanitized.shift();
    }

    const geminiBody = {
      contents: sanitized,
      generationConfig: {
        temperature: 0.7,
        maxOutputTokens: 8192,
      },
    };

    const sysPrompt =
      systemPrompt || messages.find((m) => m.role === "system")?.content;
    if (sysPrompt) {
      geminiBody.systemInstruction = { parts: [{ text: sysPrompt }] };
    }

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${modelId}:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(geminiBody),
      }
    );

    if (!response.ok) {
      const err = await response.json();
      return Response.json(
        { error: err.error?.message || "Gemini API Error" },
        { status: response.status }
      );
    }

    const data = await response.json();
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!text) {
      return Response.json(
        { error: "No response generated by Gemini." },
        { status: 500 }
      );
    }

    return Response.json({
      choices: [{ message: { role: "assistant", content: text } }],
    });
  } catch (error) {
    console.error("API Error:", error);
    return Response.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}
